name: deploy cargo docs
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install libudev-dev
        run: sudo apt-get install -yq libudev-dev
      - name: compile docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - name: deploy ghp
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
